### ISSUE TITLE
We tried implementing your method, everything works fine but multiple OTP's are triggered at same time.

### ISSUE THREAD

**Issue by metadimensions** [ykbryan/aws-amplify-react-auth-otp#12]
If we give a mobile number it says it's verifying, but we get at least 3-4 different OTP's when it's triggered.

**Comment by URVL** [comment]
@ykbryan 
I have the same problem - if no one logs into the system within 10-15 minutes, then 4-5 OTP codes come in a row, if within 10-15 minutes they log in, they send 1 OTP code, do you have ideas for solving this problem?

**Comment by URVL** [comment]
> If we give a mobile number it says it's verifying, but we get at least 3-4 different OTP's when it's triggered.

@venkimanian1995  https://github.com/aws-amplify/amplify-js/issues/4805#issuecomment-581127093

**Comment by ykbryan** [comment]
thanks @URVL for the solution
